import type { Metadata } from 'next'
import { Montserrat } from 'next/font/google'
import './globals.css'
import { AppProvider } from './providers'
import { cn } from '@/shared/lib'

const inter = Montserrat({ subsets: ['latin'], variable: '--font' })

export const metadata: Metadata = {
  title: 'Crypto Trading',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className={cn(inter.className, ' bg-background antialiased ')}>
        <AppProvider>{children}</AppProvider>
      </body>
    </html>
  )
}
